apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - immich/namespace.yaml
  - immich/sealed-secret.yaml
  - immich/helmrepository.yaml
  - immich/pv.yaml
  - immich/pvc.yaml
  - immich/cloudnative-pg/flux-kustomization.yaml
  - immich/postgres/flux-kustomization.yaml
  - immich/helmrelease.yaml
