---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-discord
  namespace: monitoring-ns
spec:
  encryptedData:
    alertmanager.yaml: AgANGN4XXWJWZY1Cu9ay4THZSITKGJBK2DmpdSsxTfyjrZOYYnp8lToK45DsZK8ZuO2Xg4X8VeqY2sHnZb9y2KOK9L82xjHM0TWdD0X/YgDUkfXUL9nFh4vxqmJ8LfFNmpQuw6jfuLhHuQWJj8FxRSGdbBoUdMcQ9RQMLIwS2TbdVRMvZC9b2oCycSAuKfWQJQDdej+sWuvfpVGYoRlNy6BpPp3wcpk3mpTw/jYekrhEuxz7prRQLgBrxS80XmqQyrE/utxGVtuW9ZA5KQ3ZlUhF4le9ygeFxHsjPaFQO0Zvs34EZ6+fU+VpTjGfPYtiJugH3ycw2tMaWv6kp2NZLxMrP03Db/w3NJdZc9DHNTIUZKCyAt1qPG+lHuv8s61hwWtFUaLZst43BbHHmfUrl5dFnF3AT9FQZv46MtwpN7YhyeBzfHA7k+gTYASp+kaAbOTI3EAmg+pmp9sZK02IJTu7AguaVoHLlLhbAYbmvy4r0BrFfTDBDJFG0+pO09icVdag+xiPKBGhPs0cfZ0SLh2/zngMIJ1OcgVYduksgboeZ7xKwJ/IazWaVnuuqztEXJCXiXt8+tndKB9TRtluJvQHqXnZSF3CfecspXhQCfS0llXb8MiP7k5cR6MsDTEkR8K4e2Mg3+9i/XvVxXrZ3CCnJGZSHsFpLzxP+YXcrXFFzWqD8R7IetX9BHfg3x10tmwLXtYyh2nMRu5AYo4kZ8YUUI2d9Mq+r1oxHfBsJi0XQNatV5LCsCR2fC529q1TX7fguu/dbxChz9RaiMewnmN8rwcyKt3fTdx7xni5dPuJgUnDGStkvlyOWPzwH5RLCYdkq5fZyW5tq2ij1tDnnsou9LjEwIcosNjFbDSI+ASuLEZbsz7aPSCZErsweWyjgA+XebfjteYWO0dLuSAPN6+oncDPx7AfRnDxTrBYNx3IQtksBz6byvAAVItt1QKpKI86y9bjcJvv0zgtRtbLMGbkzM8yJ/tVIKiPbb9CJsvryJmKgs2W049UczqYEWW/evuLFGLprpFElq5qWy/ZWVzpwAwUIRpTZ55OjNFsQZGCc6QzIRhT2QbjMkc3xc/auJnkM8kl/t+CQHGbha1FFDk0o5wvdBLnDsn/LbiGHwCJ0FWvetr2s6j0rrTTCPaFJTTLk94lhQQ91EDW4Ki/5CxJsihqoEkWGiV6q9cQvqKD7kgOcQVN6NtsMIdWtseUIPVwavoDilP76ph05z34nbnmCrSw+LvrtoEkv2gJtFfrma5kFtjkZr3OH9TQM76VWorwLSMB19XxQQ==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-discord
      namespace: monitoring-ns
