---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: monitoring-ns
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAihpi3AZQ62y9pYYBFmjDqKbX8AR5bqQkK5EwlalRANhlUtTVnYTxZ2t/+NYXwO2mK6NAa2Yls/C5yQROg4fDlNXoH0XjM+hArKWDheiftA/MNATlWkqE6MQIIaWE9H03I+wKxTT5KpnL0TDcZqWHB3ES3gIRSvxDoWkDEyvoNzsQQd1KnuYA61u45aD9I6F77IvIbOinfqszEwIiuK1ajIUg0JTdZCczko000lvRE6BtJeJt3czHmrYgdyD+XK+i82BiUYPCxUqD0sg2M/fNE0MUJ1cG/6F9hRXZmQdDreM99/w29Hm39lQxcpXiwHJ6EDGW8knobB9iGzV9W7kM8jU/clrQa1iOjof9BXTYd7++vN/E3m4Or3qSn2bwtIAHr7V2L1SG2ySouNJcSLec4tOLBmi1h+6tlrfRFJ9RUIFlLO61YZDfjXclXjWQ6e2Zu5BZa3nLtPIDxZf3+g2j7onpy2EY8Qhdt1Acoy30elIWqOrztAWmABBnzW7sDVYQYOeV+//PiEcR3HZX7X5gy++LNbbt02Pv47uSa0iRFzm++3u1rcFl84jo4QlW7d58lcdLvVCD1lrP+anXA5WoBaBQCxqwDR6KqtyQvv+1Mfmv6NBt/uKww1vwcSpgP1dy3jVRWpYrMnOAPliNJJbaU2KSJ5CsRPOHGmOMQ6JbLyJPATSd++Pg/IyCguOiNbg1luPTrQWn8UoZDSqnRa9lVASi39fwWcFBnBR7KSASolDaZQIWTLgLnCvcxBZcdJpHavqNDG/zV3IxA8DB7EvV5/8GxsR2SeyVABqzEimLIKibeyMiQz0UHQfA+qmeSULBYx9dOxCVnhzAvuUlt7VHei1HNv/BtqCtU
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: monitoring-ns
