---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: holmesgpt-secrets
  namespace: holmesgpt
spec:
  encryptedData:
    gemini-api-key: AgAMV2MInMJOjaxo7bsIK7NbdBkmZxR69U92LiP66Qq4ufjnOjjpRMZkw/dwBoaEhav+W7mUJc6uVHajZUDA9RGDshs+OxmaxNJW80cOD3VXA1JW3BTIokLKkV3QzqXyLtCPfI1mkIs69Es/dhXo7oyaqnFONJ9Sy9w5/OEEOZ7ZmOKUoObCyyVt7NLZH4JPG14h3tGw9gftadDQjArIToxL566X1zG2PzqurQ23nwfo4b6GYoKYnRkeIcupdXcVA9R2Zi4oSR4Gh1IIZs7ncOn1g/PzV3oOdKEGU//3US4s3+LASibiP05RHO1iIdN3Aco8eyrB0N7Bw4ejuaDToSGw/DRZiqCUALbqi/igYeLF9rzpwB5HQW973wYZG4rDNSYF9fh1RwgDzR497LBBQeR4BlyAhseUHd8VHLcxr/wdT94FrZJ9LEpMn/qq7JX430HudI6Kuk/a1e3mcYjR90JroBs0zgp4mKjG6miG6xDZQ1E0yFFXdManzADHiRyJI4G/iIdq0MBilb8FHEyuSCOQmWernZBw0QGlXih5lu/oiw4tz4k5EqYOZPSaTcK+n6T9wl1WKJCaGpiLeaEUQq3Lm/B0cSJ6YC6ocsOXkvEjNrqwSd3+Ztl/XZCx4AT/ownFovCXc3lgfac5sDRmiaKucWPEGjaiZbiKI2m+XbzYvCL1cSwbsBpM34EIFm2W6e9NnSVa+VuFeHh2mp+ZfLHaP/2pJH76bJvoenRnZEvWL0VxP5q5oB4=
  template:
    metadata:
      creationTimestamp: null
      name: holmesgpt-secrets
      namespace: holmesgpt
