---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meetily-secrets
  namespace: meetily
spec:
  encryptedData:
    api-secret-key: AgAdE/CYSoaShjxgB33cn4AIfzzwrqQCv/n/EZk9BRjNwVbthJoXtS+yvs4KUEjxB1pMHVpO7BWTibSTkOFneM0ENTmCSDWIN6OXi8Lc513cRyzVQSiAdOMBPF79hJ5GV7ZQ6HT/MhN8KjsWQAG5x3XgtX3UQj1MsOLS/H8oIpGkQOeAg1c7SuDrfTMeUwextSQoiptFEL44yAPRgaIE4btpw//VH2ud3M2RHveXmJ7x39RQTSxb5VX7Bk+Y2gBqnDPFEphjkhIa0WQQ1O+H5UzdRfrNyZ1bRCLfC8iArHF2I9GSg87ULQiKEnAfGiH5JKHMPKZJyKshya/cOHRkwyVzUaWs69gnFzOQYdT8SVEAXRIj4mFnycXmzuY0FrQu8C1YPtjulD7Rd7UuPCE8qesM/yDtTQsICtOLNvzAD/Ca+p+qE7hvOAwxJL4J3tU4IFFCaBJffAOn1iXba6WGQVUU/EYfhukL0aQ00+lzm9ZLL+J3wEne/3RNOwU/Vg4LTi0nv0XkyivKCpR7MVDOEmmFZMxssk0PQBr/EU6iD7QBhH1YtkmLTWXeGgukB/KZ5o0ebpGZ7rg3dMcfPdsIpEGg+pXq1mxZkqsNe3hc5/BGOs9xO4yekzmHfm4NBAgWL58iMe9AqluOChBRNp3p9/MlnqxGBGqEQVZCMtDveCaKfkFbE1q6+rUz1IrN+4i622Ertl1ISgZU6Dygmw==
    gemini-api-key: AgCfv1iKueP+XtJ/9j3oJWuobDptR38sX7CfkqfRULebM0JIyGd7+9HDwJK4AvUeUdZnpw7fL7/FVheoAkb/vP71P+N4RStT1tkpLXAdi/roG4sx5ZlAiprS318CB7GS0caOhKg8KjDyp0lQYHRYZ4KUNAQI4Xi3lOavuMnDdOiLAFHP9fm8Fa6IekQ7nkAFPXG+XxO9uAzwbLG4tA5imfYNmsgAsTAuwOqhT8P5dGn0STiQIoSTiKUdcikJzHnn++jflvA7X+v4a3upzhuXlMfnZwHj6B0QWHO80Eh5AS9G2z9LT1ZfJiam5rLHuuE6BTMrRuH/uVvLSqvKV7LUqXh383is7zOsJco68tmwCkTUn3DHVAu9pMT6jNpBil9u1gwMqtS0+uZ+IKfHOiePoqg0PCCnzclFC6XStToQDbz0ZoEojxqxOdRB2C6QG5Zd4F1jMHbJTloL7hBE4Eujx7mKKiLYYYfpMkC1Px+CXcSSGyqUrdy4VIpInDg9Sca2SOGPw9IJkv9FLX5srPoYts7WWrbGFsa/P63UFWiDm4l8RLqtiKnjp1ny181J0ezZe2z0uZFmIFcbHIalwCwg72LI7aeTESAwk69nBLPC6sPl+hIaOIZ49d0k+ieDyFX2DJqd4B8bHYvzN4oqXb/CPsbyevJx3VNhnpmVfM8jmKft8Y/cNszNrPoRyu/Ceu78+tizb9N334yklEd9T09dfrGZhL2L/KvsVu9aKoAOK6h/1pJY3DhxkpQ=
  template:
    metadata:
      creationTimestamp: null
      name: meetily-secrets
      namespace: meetily
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: meetily
spec:
  encryptedData:
    .dockerconfigjson: AgAmBFqBDrmPptSxnElvx9S1mJPq9xx43t8sbAGvU8JZ3iuGC4yLMqUVqi3LEFBhIlBkoqc6n9ywFNBAfPlQohjneaJAOBr59/6vpxVPkdpKtiYLQ6HACVMTWYUZPImydG4tnLU5CmpNrkzuyAB9DXcPV5+EsCrIdrc2QkwOwobi4A93MFm/TQjuy71gYx8C1BOkzD6CBfw0C0gLi/clsg9y8HpfttTNtiLcXWQWYdbgj4veF6XuvA/xKEdLAVfhbsQGSBU8dFaiaxZFTuwXclQIzwL3RAuZ5Vck5grG8IqIGLLjK8HXT7PTBnCgJP9rjBHlx7ez4l57GudgIlo6TmB/GsL2wNYkzgt6MMrBOW2oZcxQ6Bx7DzlgiyIpyp/9LWKsRF350pzw0FA7nX6T9/FAF1MniNe5WEEVmAUfP2wpN7NpiwkyRts0Ywn3KA2QMqPnC+SyRqZX9uPfGJ2MUcvR5WfwBXJ1uLGJ8Er2MFq8UPV0maVFqPWEiORcBO097mfxj3Eb4CS4YjxQvqrpVOWdpIwNc0NVroMk1Y1o59V3p4DWpx7TpT1S3cZqAO1xaIGAb2WnYqnL9p+j1jiysFwOKOeMalYvqH7Zv3mbVRCn87PwrXVF9ajLCtZ1U/BYFrp1BPrPt/unEXmszp0lVZUliDbGNIZXwXNQpAHcTU00jOKhz7CcAFW+veuvZALTLR4GjLbpuAegW1/pNzVAy1Cg2+jXZNaMIT5EwrEufpyuKRn4ODY4Eo1rQPNNLHtC0KWmeZ5FisIsE1fbC8/WGmJXW3Dweqysfv32lYQwZGYpo0538GgNZHZsH59NFQB9VJ3hqN/L+p/MR9CidH2glmqfnKdjyyjxh/32QZy32KovgOAHK0+L4XWg9FY/HxYV4wikjE+Zp2yHBxHvVfUjLBFdQPPGduLC8AkiIiQ/QRSX3L7J
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: meetily
    type: kubernetes.io/dockerconfigjson
