apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discord-webhook-sealedsecret.yaml
  - grafana-dashboard-zepp-activity.yaml
  - grafana-dashboard-zepp-overview.yaml
  - grafana-dashboard-zepp-recovery.yaml
  - grafana-dashboard-zepp-sleep.yaml
  - grafana-influxdb-sealedsecret.yaml
  - grafana-sealed-secret.yaml
  - helmrelease.yaml
  - influxdb-datasource.yaml
  - prometheusrule-custom.yaml
