---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBwnyztd+60wY6yds5DTgAG8qtw7DorOXQNMNHBNYzEx4Ppd4bAru8G8oe5ZBVrudeNTTvMGsdrZmzytPE4nwq+u7ZA/mfdYbBd1x4UQ/3yiSIZkh1XNzoonWCFa/mVGnwEO2fUQBgPh7eSQN61wvwXlxovVYvSDL0U4dO8NIWk2VgXGi3VNpGPr0YMSixh83SQPTThL7VivGYso4KBDEkMzcds9mmhTk18cSbezt0A62erBCo+RI+cOmVxRiSMtFoi2ArC9hKWhkew5JJE29rsSOO96fQ5dPXAKejERolw1roP22dpvhPK+ydknxEiixV0GQskTWYWUHQvijtBSrHmXZ/cBUBa3y2HgtjHNetDEgre/dF9tDpCzeaa0P+iP1ahuoRFuPONIObC+0YvFSV94XMb8sjfYfkpOlPI7zHrd3aUK6YHA0+uEFig2OTdWhJXX8NPpwOh3kPMqZhJlnjeun3lqapppyC5/jwpWM8ddjcPi6NISDd49ut+3tl+ufE/hW+Dv21PkP0FEsLdCR8uninUqpWpaoCk2tE7dl5L33aKsCJdJVwtyWK7xynSaD2IP9aOYluUL8HlH/emTCO4155/WJoMPm680H6+81Mw+v5M43Yy25ztO9LSZ6zAngUfxE5Rhv+wjSa2vvgLkgNQwOuH/HfyEjrcfHoMDNHMKK/aL11MovrcqSGFjiAHZZPpgmmHGOdcEYtDCehDV/UC+zCQvsEOQizoSUvsV28i9cB/10MFsA6v5vHqRRUb1fEsKl189A==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
